In [1]:
import pandas as pd
import numpy as np
# from Analytical_Functions import * 
import matplotlib 
from matplotlib import pyplot as plt

In [3]:
main_df = pd.read_csv('data/main_table.csv')
hh_df = pd.read_csv('data/hh_roster.csv')
ext_df = pd.read_csv('data/mig_ext_roster.csv')
lut = pd.read_csv('data/answer_lookup.csv', usecols=[0,1,2,3], index_col='label')
lut = lut.rename(columns={'text_content':'response'})
main_lut = pd.read_csv('data/main_lookup.csv', index_col='label')

In [2]:
df = pd.read_csv('vars_of_interest_v2.csv',index_col=0)

In [111]:
df

,avg_income_currency,avg_income_amount,AVG_INCOME_USD,country,rural_urban,remesa_currency,remesa_amount,REMESA_AMOUNT_USD,remesa_freq,REMESA_AMOUNT_REGPERMONTH,...,pct_remit_towards_Housing(constructionorrepair),pct_remit_towards_Housingrentalfee,pct_remit_towards_Homepurchasefee,pct_remit_towards_Purchaseofagriculturalinputs,pct_remit_towards_Business(trade),pct_remit_towards_Saving,pct_remit_towards_Paymentofcommitmentsofmembersresidingabroad,pct_remit_towards_Paymentofthesender'straveldebt,pct_remit_towards_Paymentofotherdebts,pct_remit_towards_Other
0,NaN,NaN,NaN,SLV,2,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1.0,500.0,500.000,SLV,2,NaN,NaN,NaN,3.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1.0,300.0,300.000,SLV,2,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1.0,350.0,350.000,SLV,2,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1.0,347.0,347.000,SLV,2,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4993,3.0,260.0,10.660,GT,2,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4994,3.0,247.0,10.127,GT,2,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4995,3.0,650.0,26.650,GT,2,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4996,3.0,65.0,2.665,GT,2,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4997,3.0,195.0,7.995,GT,2,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
df['hh_size'] = main_df.hh_size

In [5]:
df.loc[df.hh_size == 0,'hh_size'] = 1

In [6]:
df['AVG_INCOME_USD_PERCAP'] = df['AVG_INCOME_USD'] / df['hh_size']

In [7]:
df['REMESA_AMOUNT_REGPERMONTH_PERCAP'] = df['REMESA_AMOUNT_REGPERMONTH'] / df['hh_size']

In [8]:
df.loc[:,[col for col in df.columns if 'pct_remit_towards' in col ]] = df.loc[:,[col for col in df.columns if 'pct_remit_towards' in col ]].fillna(0)

In [9]:
regremit_and_consent_df = df.dropna()

In [10]:
regremit_and_consent_df.to_csv('reg_remit_and_consent_v1')

In [13]:
sampled_df = regremit_and_consent_df.groupby(['country','rural_urban']).sample(n=100,replace=True)

In [14]:
sampled_df.columns

Index(['avg_income_currency', 'avg_income_amount', 'AVG_INCOME_USD', 'country',
       'rural_urban', 'remesa_currency', 'remesa_amount', 'REMESA_AMOUNT_USD',
       'remesa_freq', 'REMESA_AMOUNT_REGPERMONTH', 'remittances_yn',
       'remesa_amount_consent', 'avg_income_consent',
       'pct_remit_towards_Foodpurchase',
       'pct_remit_towards_Healthexpenses(medicines/medicalconsultation)',
       'pct_remit_towards_ExpensesrelatedtoCOVID-19(protectionsupplies,medicalconsultation,medicines)',
       'pct_remit_towards_Educationexpenses',
       'pct_remit_towards_Paymentofservices(water,electricity,cable,internet,communication)',
       'pct_remit_towards_Clothesandshoes',
       'pct_remit_towards_Housing(constructionorrepair)',
       'pct_remit_towards_Housingrentalfee',
       'pct_remit_towards_Homepurchasefee',
       'pct_remit_towards_Purchaseofagriculturalinputs',
       'pct_remit_towards_Business(trade)', 'pct_remit_towards_Saving',
       'pct_remit_towards_Paymentofcommitmentsofmembersresidingabroad',
       'pct_remit_towards_Paymentofthesender'straveldebt',
       'pct_remit_towards_Paymentofotherdebts', 'pct_remit_towards_Other',
       'hh_size', 'AVG_INCOME_USD_PERCAP', 'REMESA_AMOUNT_REGPERMONTH_PERCAP'],
      dtype='object')

In [15]:
sampled_df = sampled_df.drop(columns=['avg_income_currency','avg_income_amount','country','rural_urban','remesa_currency','remesa_amount','remittances_yn','remesa_amount_consent','avg_income_consent'])

In [18]:
sampled_df.iloc[0]

AVG_INCOME_USD                                                                                     4.264000
REMESA_AMOUNT_USD                                                                                300.000000
remesa_freq                                                                                        7.000000
REMESA_AMOUNT_REGPERMONTH                                                                         25.000000
pct_remit_towards_Foodpurchase                                                                    50.000000
pct_remit_towards_Healthexpenses(medicines/medicalconsultation)                                    0.000000
pct_remit_towards_ExpensesrelatedtoCOVID-19(protectionsupplies,medicalconsultation,medicines)      0.000000
pct_remit_towards_Educationexpenses                                                                0.000000
pct_remit_towards_Paymentofservices(water,electricity,cable,internet,communication)                0.000000
pct_remit_towards_Clothesandshoes                                                                 50.000000
pct_remit_towards_Housing(constructionorrepair)                                                    0.000000
pct_remit_towards_Housingrentalfee                                                                 0.000000
pct_remit_towards_Homepurchasefee                                                                  0.000000
pct_remit_towards_Purchaseofagriculturalinputs                                                     0.000000
pct_remit_towards_Business(trade)                                                                  0.000000
pct_remit_towards_Saving                                                                           0.000000
pct_remit_towards_Paymentofcommitmentsofmembersresidingabroad                                      0.000000
pct_remit_towards_Paymentofthesender'straveldebt                                                   0.000000
pct_remit_towards_Paymentofotherdebts                                                              0.000000
pct_remit_towards_Other                                                                            0.000000
hh_size                                                                                            7.000000
AVG_INCOME_USD_PERCAP                                                                              0.609143
REMESA_AMOUNT_REGPERMONTH_PERCAP                                                                   3.571429
Name: 3387, dtype: float64

In [20]:
sampled_df.describe()

,AVG_INCOME_USD,REMESA_AMOUNT_USD,remesa_freq,REMESA_AMOUNT_REGPERMONTH,pct_remit_towards_Foodpurchase,pct_remit_towards_Healthexpenses(medicines/medicalconsultation),"pct_remit_towards_ExpensesrelatedtoCOVID-19(protectionsupplies,medicalconsultation,medicines)",pct_remit_towards_Educationexpenses,"pct_remit_towards_Paymentofservices(water,electricity,cable,internet,communication)",pct_remit_towards_Clothesandshoes,...,pct_remit_towards_Purchaseofagriculturalinputs,pct_remit_towards_Business(trade),pct_remit_towards_Saving,pct_remit_towards_Paymentofcommitmentsofmembersresidingabroad,pct_remit_towards_Paymentofthesender'straveldebt,pct_remit_towards_Paymentofotherdebts,pct_remit_towards_Other,hh_size,AVG_INCOME_USD_PERCAP,REMESA_AMOUNT_REGPERMONTH_PERCAP
count,600.000000,600.000000,600.000000,600.000000,600.000000,600.000000,600.000000,600.000000,600.000000,600.000000,...,600.00000,600.000000,600.000000,600.0,600.000000,600.000000,600.000000,600.000000,600.000000,600.000000
mean,154.218515,123.584125,3.636667,138.028170,50.313333,12.800000,0.463333,3.075000,11.625000,2.550000,...,0.27500,0.491667,1.358333,0.0,1.233333,0.183333,0.991667,4.548333,41.544691,36.569807
std,256.590602,266.940002,1.449652,339.980659,32.961127,23.064329,3.618999,13.786569,18.723835,8.758349,...,2.56131,5.386553,8.355415,0.0,9.107715,3.486160,8.426740,2.152220,75.731620,79.087580
min,0.000000,0.533000,1.000000,0.222083,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.00000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,1.000000,0.000000,0.044417
25%,15.990000,10.660000,3.000000,7.995000,30.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.00000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,3.000000,3.331250,1.666406
50%,37.843000,50.000000,3.000000,31.980000,50.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.00000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,4.000000,10.660000,8.333333
75%,200.000000,150.000000,5.000000,120.000000,75.000000,20.000000,0.000000,0.000000,20.000000,0.000000,...,0.00000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,6.000000,50.000000,33.333333
max,3000.000000,5000.000000,7.000000,5000.000000,100.000000,100.000000,50.000000,100.000000,100.000000,50.000000,...,25.00000,100.000000,100.000000,0.0,100.000000,80.000000,100.000000,14.000000,1000.000000,833.333333

In [21]:
sampled_df.to_csv('sampled_v1')